spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # TiDB não precisa de validação
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        # Importante para TiDB
        hibernate.jdbc.lob.non_contextual_creation: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false  # Desative para TiDB
    locations: classpath:db/migration

  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Lisbon

server:
  servlet:
    context-path: /smart-marisco-api

logging:
  level:
    mz.com.sgp: DEBUG
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

cors:
  originPatterns: "*"