spring:
  application:
    name: smart-marisco-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false

    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Europe/Lisbon

server:
  servlet:
    context-path: /smart-marisco-api

logging:
  level:
    mz.com.sgp: DEBUG

cors:
  originPatterns:  "*"