-- ============================================
-- 1. Tabela CATEGORY
-- ============================================
CREATE TABLE `CATEGORY` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_BY` VARCHAR(20),
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `NAME` VARCHAR(80) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;

-- ============================================
-- 2. Tabela SPECIES
-- ============================================
CREATE TABLE `SPECIES` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) NOT NULL,
    `UPDATED_BY` VARCHAR(20) ,
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `CATEGORY_ID` BIGINT NOT NULL,
    `NAME` VARCHAR(80) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_PRODUCT_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY`(`ID`)
) ENGINE = InnoDB;

-- ============================================
-- 3. Tabela UNIT
-- ============================================
CREATE TABLE `UNIT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `NAME` VARCHAR(100) NOT NULL,
    `SYMBOL` VARCHAR(10) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_UNIT_SYMBOL` (`SYMBOL`),
    UNIQUE KEY `UK_UNIT_NAME` (`NAME`)
) ENGINE = InnoDB;

-- ============================================
-- 4. Tabela PRODUCT
-- ============================================
CREATE TABLE `PRODUCT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) NOT NULL ,
    `UPDATED_BY` VARCHAR(20) ,
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `CODE` VARCHAR(255) NOT NULL,
    `SPECIES_ID` BIGINT NOT NULL,
    `NAME` VARCHAR(80) NOT NULL,
    `DESCRIPTION` VARCHAR(255) NOT NULL,
    `PRICE` DECIMAL(10,2) NOT NULL,
    `SALE_PRICE` DECIMAL(10,2) NOT NULL,
    `IMAGE` LONGTEXT,
    `UNIT_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_PRODUCT_SPECIES` FOREIGN KEY (`SPECIES_ID`) REFERENCES `SPECIES`(`ID`),
    CONSTRAINT `FK_PRODUCT_UNIT` FOREIGN KEY (`UNIT_ID`) REFERENCES `UNIT`(`ID`),
    UNIQUE KEY `UK_PRODUCT_CODE` (`CODE`)
) ENGINE = InnoDB;
