CREATE TABLE IF NOT EXISTS `CLIENT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL,
    `CREATED_BY` VARCHAR(20),
    `UPDATED_BY` VARCHAR(20),
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `FIRST_NAME` VARCHAR(80) NOT NULL,
    `LAST_NAME` VARCHAR(80) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
    `PHONE_NUMBER` VARCHAR(15) NOT NULL,
    `EMAIL` VARCHAR(100),
    `TYPE` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ID`)
);