-- ============================================
-- 1. Tabela STOCK
-- ============================================
CREATE TABLE `STOCK` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `PRODUCT_ID` BIGINT NOT NULL,
    `QUANTITY` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_STOCK_PRODUCT` (`PRODUCT_ID`),
    CONSTRAINT `FK_STOCK_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`ID`) ON DELETE CASCADE
) ENGINE = InnoDB;

-- ============================================
-- 2. Tabela STOCK_MOVEMENT
-- ============================================
CREATE TABLE `STOCK_MOVEMENT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `STOCK_ID` BIGINT NOT NULL,
    `MOVEMENT_TYPE` ENUM('ENTRY','EXIT') NOT NULL,
    `QUANTITY` DECIMAL(10,3) NOT NULL DEFAULT 0.000,
    `DESCRIPTION` VARCHAR(255) NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_MOVEMENT_PRODUCT` FOREIGN KEY (`STOCK_ID`) REFERENCES `STOCK`(`ID`) ON DELETE CASCADE
) ENGINE = InnoDB;