CREATE TABLE `SALE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `CLIENT_ID` BIGINT ,
    `SALE_STATUS` VARCHAR(20) NOT NULL,
    `TOTAL_VALUE` DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_CLIENT_SALE` FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENT`(`ID`) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE `SALE_ITEM` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `SALE_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NOT NULL,
    `QUANTITY` DECIMAL(10,3) NOT NULL DEFAULT 0,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_SALE_ITEM_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`ID`) ON DELETE cascade,
    CONSTRAINT `FK_SALE_ITEM_SALE` FOREIGN KEY (`SALE_ID`) REFERENCES `SALE`(`ID`) ON DELETE CASCADE
) ENGINE = InnoDB;
