ALTER TABLE USERS ADD COLUMN TOKEN_VERSION BIGINT NOT NULL DEFAULT 0;

CREATE TABLE AUTH_REFRESH_TOKEN (
    TOKEN_ID VARCHAR(36) NOT NULL PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    EXPIRES_AT TIMESTAMP(6) NOT NULL,
    INDEX IX_REFRESH_EXPIRY (EXPIRES_AT),
    CONSTRAINT FK_REFRESH_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Disable only the original seeded credential; preserve accounts with changed passwords.
UPDATE USERS SET ENABLED = b'0', TOKEN_VERSION = TOKEN_VERSION + 1
WHERE USER_NAME = 'admin'
  AND PASSWORD = '{pbkdf2}d1655d5ac31b92342b58152d794f19adf7e9965a3b9a270ee90d7e2c009302d4b41c3b3ceeee88cb';
