CREATE TABLE SALE_OPERATION (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    REQUEST_KEY VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    REQUEST_HASH VARCHAR(64) NOT NULL,
    RESPONSE_JSON TEXT NOT NULL,
    CONSTRAINT UK_SALE_OPERATION UNIQUE (USER_ID, REQUEST_KEY),
    CONSTRAINT FK_SALE_OPERATION_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
) ENGINE=InnoDB;
