ALTER TABLE SALE_ITEM ADD COLUMN UNIT_PRICE DECIMAL(19,2) NULL;
ALTER TABLE SALE ADD COLUMN ORDER_RECORD BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN STOCK_DEDUCTED BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN EDIT_REVISION BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN VERSION BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN COMPLETED_DATE TIMESTAMP NULL;
-- The previous implementation deducted stock for every existing order.
UPDATE SALE SET ORDER_RECORD = TRUE WHERE SALE_STATUS = 'ORDERS';
UPDATE SALE SET STOCK_DEDUCTED = TRUE WHERE SALE_STATUS IN ('ORDERS', 'COMPLETED');
UPDATE SALE SET COMPLETED_DATE = CREATED_DATE WHERE SALE_STATUS = 'COMPLETED';
-- Historical item prices cannot be reconstructed reliably. Keep NULL rather than inventing prices.
